-- Curated races for races_catalog (run manually in Supabase SQL Editor after migration 029).
-- Safe to re-run if you TRUNCATE races_catalog first.

INSERT INTO races_catalog (name, sport, category, race_date, city, country) VALUES
-- HYROX (major cities; dates illustrative / announced-style)
('HYROX Miami', 'hyrox', 'Open', '2026-03-14', 'Miami', 'USA'),
('HYROX Washington DC', 'hyrox', 'Open', '2026-09-05', 'Washington DC', 'USA'),
('HYROX Chicago', 'hyrox', 'Open', '2026-04-18', 'Chicago', 'USA'),
('HYROX Los Angeles', 'hyrox', 'Open', '2026-05-09', 'Los Angeles', 'USA'),
('HYROX Dallas', 'hyrox', 'Open', '2026-06-20', 'Dallas', 'USA'),
('HYROX Houston', 'hyrox', 'Open', '2026-07-11', 'Houston', 'USA'),
('HYROX Atlanta', 'hyrox', 'Open', '2026-08-08', 'Atlanta', 'USA'),
('HYROX Boston', 'hyrox', 'Open', '2026-09-19', 'Boston', 'USA'),
('HYROX New York', 'hyrox', 'Open', '2026-10-10', 'New York', 'USA'),
('HYROX Toronto', 'hyrox', 'Open', '2026-11-07', 'Toronto', 'Canada'),
('HYROX London', 'hyrox', 'Open', '2026-04-25', 'London', 'UK'),
('HYROX Amsterdam', 'hyrox', 'Open', '2026-05-30', 'Amsterdam', 'Netherlands'),
('HYROX Berlin', 'hyrox', 'Open', '2026-06-13', 'Berlin', 'Germany'),
('HYROX Dubai', 'hyrox', 'Open', '2026-11-21', 'Dubai', 'UAE'),
('HYROX Singapore', 'hyrox', 'Open', '2026-12-05', 'Singapore', 'Singapore'),
('HYROX Sydney', 'hyrox', 'Open', '2026-08-22', 'Sydney', 'Australia'),
('HYROX Melbourne', 'hyrox', 'Open', '2026-09-12', 'Melbourne', 'Australia'),
('HYROX Paris', 'hyrox', 'Open', '2027-01-16', 'Paris', 'France'),
('HYROX Madrid', 'hyrox', 'Open', '2027-02-06', 'Madrid', 'Spain'),
('HYROX Barcelona', 'hyrox', 'Open', '2027-03-13', 'Barcelona', 'Spain'),
('HYROX Stockholm', 'hyrox', 'Open', '2026-10-24', 'Stockholm', 'Sweden'),
('HYROX Copenhagen', 'hyrox', 'Open', '2026-11-14', 'Copenhagen', 'Denmark'),
('HYROX Vienna', 'hyrox', 'Open', '2027-04-10', 'Vienna', 'Austria'),
('HYROX Hong Kong', 'hyrox', 'Open', '2027-05-08', 'Hong Kong', 'China'),
('HYROX Tokyo', 'hyrox', 'Open', '2027-06-12', 'Tokyo', 'Japan'),

-- Triathlon / Ironman
('Ironman World Championship Kona', 'triathlon', 'Ironman', '2026-10-10', 'Kailua-Kona', 'USA'),
('Ironman Texas', 'triathlon', 'Ironman', '2026-04-25', 'The Woodlands', 'USA'),
('Ironman Florida', 'triathlon', 'Ironman', '2026-11-07', 'Panama City Beach', 'USA'),
('Ironman Lake Placid', 'triathlon', 'Ironman', '2026-07-26', 'Lake Placid', 'USA'),
('Ironman Arizona', 'triathlon', 'Ironman', '2026-11-22', 'Tempe', 'USA'),
('Ironman California', 'triathlon', 'Ironman', '2026-05-02', 'Oceanside', 'USA'),
('Ironman European Championship Frankfurt', 'triathlon', 'Ironman', '2026-08-30', 'Frankfurt', 'Germany'),
('Ironman Wales', 'triathlon', 'Ironman', '2026-09-13', 'Tenby', 'UK'),
('Ironman 70.3 Oceanside', 'triathlon', '70.3', '2026-04-04', 'Oceanside', 'USA'),
('Ironman 70.3 St. George', 'triathlon', '70.3', '2026-05-02', 'St. George', 'USA'),
('Ironman 70.3 Chattanooga', 'triathlon', '70.3', '2026-05-17', 'Chattanooga', 'USA'),
('Ironman 70.3 Boulder', 'triathlon', '70.3', '2026-06-14', 'Boulder', 'USA'),
('Ironman 70.3 Lubbock', 'triathlon', '70.3', '2026-06-28', 'Lubbock', 'USA'),
('Ironman 70.3 Augusta', 'triathlon', '70.3', '2026-09-27', 'Augusta', 'USA'),
('Ironman 70.3 Waco', 'triathlon', '70.3', '2026-10-11', 'Waco', 'USA'),
('Ironman 70.3 Barcelona', 'triathlon', '70.3', '2026-05-17', 'Barcelona', 'Spain'),
('Ironman 70.3 Elsinore', 'triathlon', '70.3', '2026-06-21', 'Helsingør', 'Denmark'),
('Challenge Roth', 'triathlon', 'Long distance', '2026-07-05', 'Roth', 'Germany'),
('Escape from Alcatraz', 'triathlon', 'Olympic', '2026-06-07', 'San Francisco', 'USA'),

-- Marathons
('Boston Marathon', 'running', 'Marathon', '2026-04-20', 'Boston', 'USA'),
('TCS New York City Marathon', 'running', 'Marathon', '2026-11-01', 'New York', 'USA'),
('Bank of America Chicago Marathon', 'running', 'Marathon', '2026-10-11', 'Chicago', 'USA'),
('London Marathon', 'running', 'Marathon', '2026-04-26', 'London', 'UK'),
('Berlin Marathon', 'running', 'Marathon', '2026-09-27', 'Berlin', 'Germany'),
('Tokyo Marathon', 'running', 'Marathon', '2026-03-01', 'Tokyo', 'Japan'),
('Paris Marathon', 'running', 'Marathon', '2026-04-12', 'Paris', 'France'),
('Houston Marathon', 'running', 'Marathon', '2026-01-18', 'Houston', 'USA'),
('Chevron Houston Marathon', 'running', 'Marathon', '2027-01-17', 'Houston', 'USA'),
('Los Angeles Marathon', 'running', 'Marathon', '2026-03-08', 'Los Angeles', 'USA'),
('Philadelphia Marathon', 'running', 'Marathon', '2026-11-22', 'Philadelphia', 'USA'),
('Marine Corps Marathon', 'running', 'Marathon', '2026-10-25', 'Arlington', 'USA'),
('Big Sur International Marathon', 'running', 'Marathon', '2026-04-26', 'Big Sur', 'USA'),
('Amsterdam Marathon', 'running', 'Marathon', '2026-10-18', 'Amsterdam', 'Netherlands'),
('Toronto Waterfront Marathon', 'running', 'Marathon', '2026-10-18', 'Toronto', 'Canada'),
('Seattle Marathon', 'running', 'Marathon', '2026-11-29', 'Seattle', 'USA'),
('Austin Marathon', 'running', 'Marathon', '2026-02-15', 'Austin', 'USA'),
('Dallas Marathon', 'running', 'Marathon', '2026-12-13', 'Dallas', 'USA'),

-- Half marathons & popular distances
('Brooklyn Half Marathon', 'running', 'Half Marathon', '2026-05-16', 'Brooklyn', 'USA'),
('NYC Half', 'running', 'Half Marathon', '2026-03-15', 'New York', 'USA'),
('Rock n Roll Las Vegas Half', 'running', 'Half Marathon', '2026-02-22', 'Las Vegas', 'USA'),
('Garmin Austin Half Marathon', 'running', 'Half Marathon', '2026-02-15', 'Austin', 'USA'),
('Philadelphia Love Run Half', 'running', 'Half Marathon', '2026-03-29', 'Philadelphia', 'USA'),
('Cherry Blossom Ten Mile Run', 'running', '10 mile', '2026-04-05', 'Washington DC', 'USA'),
('Peachtree Road Race 10K', 'running', '10k', '2026-07-04', 'Atlanta', 'USA'),
('Bolder Boulder 10K', 'running', '10k', '2026-05-25', 'Boulder', 'USA'),
('Bay to Breakers 12K', 'running', '12k', '2026-05-17', 'San Francisco', 'USA'),
('Cooper River Bridge Run 10K', 'running', '10k', '2026-04-04', 'Charleston', 'USA'),
('BAA 5K', 'running', '5k', '2026-04-18', 'Boston', 'USA'),
('Credit Union Cherry Blossom 10 Mile', 'running', '10 mile', '2027-04-04', 'Washington DC', 'USA'),

-- Cycling / gran fondos
('Sea Otter Classic Fondo', 'cycling', 'Gran Fondo', '2026-04-16', 'Monterey', 'USA'),
('L''Etape du Tour', 'cycling', 'Sportive', '2026-07-06', 'Alps', 'France'),
('RideLondon Essex 100', 'cycling', 'Sportive', '2026-05-25', 'London', 'UK'),
('Belgian Waffle Ride San Diego', 'cycling', 'Gravel', '2026-05-03', 'San Diego', 'USA'),
('Unbound Gravel 200', 'cycling', 'Gravel', '2026-06-06', 'Emporia', 'USA'),
('SBT GRVL', 'cycling', 'Gravel', '2026-08-16', 'Steamboat Springs', 'USA'),

-- OCR / Spartan
('Spartan Killington Beast', 'ocr', 'Ultra', '2026-09-12', 'Killington', 'USA'),
('Spartan Tri-State Sprint', 'ocr', 'Sprint', '2026-06-06', 'Mountain Creek', 'USA'),
('Spartan Dallas Sprint', 'ocr', 'Sprint', '2026-03-21', 'Dallas', 'USA'),
('Spartan Austin Super', 'ocr', 'Super', '2026-05-09', 'Austin', 'USA'),
('Spartan Seattle Stadion', 'ocr', 'Stadion', '2026-08-01', 'Seattle', 'USA'),
('Tough Mudder Chicago', 'ocr', 'Classic', '2026-07-18', 'Chicago', 'USA'),
('Tough Mudder Atlanta', 'ocr', 'Classic', '2026-05-30', 'Atlanta', 'USA'),

-- CrossFit season (illustrative dates)
('CrossFit Open 2026', 'crossfit', 'Open', '2026-02-19', 'Worldwide', 'USA'),
('CrossFit Quarterfinals 2026', 'crossfit', 'Quarterfinals', '2026-03-20', 'Worldwide', 'USA'),
('CrossFit Semifinals North America East', 'crossfit', 'Semifinals', '2026-05-22', 'Orlando', 'USA'),
('CrossFit Semifinals North America West', 'crossfit', 'Semifinals', '2026-05-29', 'Salt Lake City', 'USA'),
('CrossFit Games 2026', 'crossfit', 'Games', '2026-08-06', 'Fort Worth', 'USA'),

-- Powerlifting / physique
('USAPL Raw Nationals', 'powerlifting', 'National', '2026-10-07', 'Denver', 'USA'),
('USPA Drug Tested Nationals', 'powerlifting', 'National', '2026-09-24', 'Las Vegas', 'USA'),
('Arnold Sports Festival Powerlifting', 'powerlifting', 'Pro', '2026-03-05', 'Columbus', 'USA'),
('NPC Universe Championships', 'bodybuilding', 'National', '2026-07-03', 'Teaneck', 'USA'),
('Olympia Weekend', 'bodybuilding', 'Pro', '2026-10-09', 'Orlando', 'USA'),

-- Additional HYROX density for search
('HYROX Las Vegas', 'hyrox', 'Open', '2027-02-20', 'Las Vegas', 'USA'),
('HYROX San Diego', 'hyrox', 'Open', '2027-03-06', 'San Diego', 'USA'),
('HYROX Seattle', 'hyrox', 'Open', '2026-12-12', 'Seattle', 'USA'),
('HYROX Denver', 'hyrox', 'Open', '2027-01-23', 'Denver', 'USA'),
('HYROX Phoenix', 'hyrox', 'Open', '2026-11-28', 'Phoenix', 'USA'),
('HYROX Nashville', 'hyrox', 'Open', '2026-10-17', 'Nashville', 'USA'),
('HYROX Orlando', 'hyrox', 'Open', '2026-11-14', 'Orlando', 'USA'),
('HYROX Tampa', 'hyrox', 'Open', '2027-01-30', 'Tampa', 'USA'),
('HYROX Minneapolis', 'hyrox', 'Open', '2026-12-05', 'Minneapolis', 'USA'),
('HYROX Detroit', 'hyrox', 'Open', '2027-02-27', 'Detroit', 'USA'),

-- More running majors & halves
('Marine Corps Historic Half', 'running', 'Half Marathon', '2026-05-17', 'Fredericksburg', 'USA'),
('Rock n Roll Nashville Half', 'running', 'Half Marathon', '2026-04-25', 'Nashville', 'USA'),
('One City Marathon', 'running', 'Marathon', '2026-03-01', 'Newport News', 'USA'),
('CIM California International Marathon', 'running', 'Marathon', '2026-12-06', 'Sacramento', 'USA'),
('Grandma''s Marathon', 'running', 'Marathon', '2026-06-20', 'Duluth', 'USA'),
('Twin Cities Marathon', 'running', 'Marathon', '2026-10-04', 'Minneapolis', 'USA'),
('Detroit Free Press Marathon', 'running', 'Marathon', '2026-10-18', 'Detroit', 'USA'),
('Columbus Marathon', 'running', 'Marathon', '2026-10-18', 'Columbus', 'USA'),
('Honolulu Marathon', 'running', 'Marathon', '2026-12-13', 'Honolulu', 'USA'),
('Valencia Marathon', 'running', 'Marathon', '2026-12-06', 'Valencia', 'Spain'),
('Rome Marathon', 'running', 'Marathon', '2026-03-29', 'Rome', 'Italy'),
('Prague Marathon', 'running', 'Marathon', '2026-05-03', 'Prague', 'Czech Republic'),
('Stockholm Marathon', 'running', 'Marathon', '2026-06-06', 'Stockholm', 'Sweden'),
('Copenhagen Marathon', 'running', 'Marathon', '2026-05-17', 'Copenhagen', 'Denmark'),
('Barcelona Marathon', 'running', 'Marathon', '2026-03-15', 'Barcelona', 'Spain'),

-- More 70.3 / Olympic
('Ironman 70.3 Santa Cruz', 'triathlon', '70.3', '2026-09-13', 'Santa Cruz', 'USA'),
('Ironman 70.3 Morro Bay', 'triathlon', '70.3', '2026-05-02', 'Morro Bay', 'USA'),
('Ironman 70.3 Victoria', 'triathlon', '70.3', '2026-05-31', 'Victoria', 'Canada'),
('Olympic Triathlon Paris Test Event Style', 'triathlon', 'Olympic', NULL, 'Paris', 'France'),

-- More Spartan / OCR
('Spartan Hawaii Trifecta Weekend', 'ocr', 'Sprint', '2026-08-15', 'Oahu', 'USA'),
('Spartan Colorado Springs', 'ocr', 'Super', '2026-07-11', 'Colorado Springs', 'USA'),
('Savage Race Maryland', 'ocr', 'Classic', '2026-06-13', 'Kennedyville', 'USA'),

-- More cycling
('Tour of Flanders Sportive', 'cycling', 'Classic', '2026-04-04', 'Oudenaarde', 'Belgium'),
('Paris-Roubaix Challenge', 'cycling', 'Classic', '2026-04-11', 'Roubaix', 'France'),
('GFNY New York', 'cycling', 'Gran Fondo', '2026-05-17', 'New York', 'USA'),
('GFNY Cozumel', 'cycling', 'Gran Fondo', '2026-11-15', 'Cozumel', 'Mexico'),

-- Duplicates avoided: more city HYROX style
('HYROX San Francisco', 'hyrox', 'Open', NULL, 'San Francisco', 'USA'),
('HYROX Portland', 'hyrox', 'Open', NULL, 'Portland', 'USA'),
('HYROX Austin', 'hyrox', 'Open', NULL, 'Austin', 'USA'),
('HYROX Charlotte', 'hyrox', 'Open', NULL, 'Charlotte', 'USA'),
('HYROX Columbus', 'hyrox', 'Open', NULL, 'Columbus', 'USA'),
('HYROX Kansas City', 'hyrox', 'Open', NULL, 'Kansas City', 'USA'),
('HYROX St. Louis', 'hyrox', 'Open', NULL, 'St. Louis', 'USA'),
('HYROX Calgary', 'hyrox', 'Open', NULL, 'Calgary', 'Canada'),
('HYROX Vancouver', 'hyrox', 'Open', NULL, 'Vancouver', 'Canada'),
('HYROX Montreal', 'hyrox', 'Open', NULL, 'Montreal', 'Canada');

INSERT INTO races_catalog (name, sport, category, race_date, city, country) VALUES
('Ironman 70.3 Gulf Coast', 'triathlon', '70.3', '2026-05-10', 'Panama City Beach', 'USA'),
('Ironman 70.3 Eagleman', 'triathlon', '70.3', '2026-06-14', 'Cambridge', 'USA'),
('Ironman 70.3 Muncie', 'triathlon', '70.3', '2026-07-11', 'Muncie', 'USA'),
('Ironman 70.3 Steelhead', 'triathlon', '70.3', '2026-08-09', 'Benton Harbor', 'USA'),
('Ironman Maryland', 'triathlon', 'Ironman', '2026-09-19', 'Cambridge', 'USA'),
('Ironman Wisconsin', 'triathlon', 'Ironman', '2026-09-13', 'Madison', 'USA'),
('Ironman Chattanooga', 'triathlon', 'Ironman', '2026-09-27', 'Chattanooga', 'USA'),
('Ironman Western Australia', 'triathlon', 'Ironman', '2026-12-06', 'Busselton', 'Australia'),
('Ironman New Zealand', 'triathlon', 'Ironman', '2026-03-07', 'Taupo', 'New Zealand'),
('Escape from Alcatraz Aquathlon', 'triathlon', 'Aquathlon', '2026-06-06', 'San Francisco', 'USA'),
('NYC Triathlon', 'triathlon', 'Olympic', '2026-07-19', 'New York', 'USA'),
('Lifetime Miami Marathon', 'running', 'Marathon', '2026-01-25', 'Miami', 'USA'),
('Gasparilla Distance Classic', 'running', 'Half Marathon', '2026-02-22', 'Tampa', 'USA'),
('Gate River Run 15K', 'running', '15k', '2026-03-07', 'Jacksonville', 'USA'),
('Credit Union Cherry Blossom 5K', 'running', '5k', '2026-04-05', 'Washington DC', 'USA'),
('BAA 10K', 'running', '10k', '2026-06-21', 'Boston', 'USA'),
('AJC Peachtree Road Race', 'running', '10k', '2027-07-04', 'Atlanta', 'USA'),
('Baystate Marathon', 'running', 'Marathon', '2026-10-18', 'Lowell', 'USA'),
('Steamtown Marathon', 'running', 'Marathon', '2026-10-11', 'Scranton', 'USA'),
('Mount Desert Island Marathon', 'running', 'Marathon', '2026-10-18', 'Bar Harbor', 'USA'),
('Wineglass Marathon', 'running', 'Marathon', '2026-10-05', 'Corning', 'USA'),
('Revel Big Cottonwood Marathon', 'running', 'Marathon', '2026-09-12', 'Salt Lake City', 'USA'),
('St. George Marathon', 'running', 'Marathon', '2026-10-03', 'St. George', 'USA'),
('Eugene Marathon', 'running', 'Marathon', '2026-04-26', 'Eugene', 'USA'),
('Flying Pig Marathon', 'running', 'Marathon', '2026-05-03', 'Cincinnati', 'USA'),
('Kentucky Derby Festival Marathon', 'running', 'Marathon', '2026-04-25', 'Louisville', 'USA'),
('Missoula Marathon', 'running', 'Marathon', '2026-06-28', 'Missoula', 'USA'),
('Deadwood Mickelson Trail Marathon', 'running', 'Marathon', '2026-06-07', 'Deadwood', 'USA'),
('Leadville Trail 100 Run', 'running', 'Ultra', '2026-08-22', 'Leadville', 'USA'),
('Western States 100', 'running', 'Ultra', '2026-06-27', 'Olympic Valley', 'USA'),
('Javelina Jundred', 'running', 'Ultra', '2026-10-31', 'Fort McDowell', 'USA'),
('Spartan Palmerton Super', 'ocr', 'Super', '2026-07-18', 'Palmerton', 'USA'),
('Spartan Asheville Sprint', 'ocr', 'Sprint', '2026-04-18', 'Asheville', 'USA'),
('Spartan Boston Sprint', 'ocr', 'Sprint', '2026-06-13', 'Boston', 'USA'),
('Spartan Utah Beast', 'ocr', 'Beast', '2026-05-30', 'Tooele', 'USA'),
('Tough Mudder Los Angeles', 'ocr', 'Classic', '2026-10-10', 'Los Angeles', 'USA'),
('Rugged Maniac Virginia', 'ocr', '5k', '2026-05-16', 'Richmond', 'USA'),
('Warrior Dash Texas', 'ocr', 'Sprint', '2026-04-11', 'Smithville', 'USA'),
('Belgian Waffle Ride Utah', 'cycling', 'Gravel', '2026-08-29', 'Cedar City', 'USA'),
('Rebecca''s Private Idaho', 'cycling', 'Gravel', '2026-09-05', 'Sun Valley', 'USA'),
('Leadville Trail 100 MTB', 'cycling', 'MTB', '2026-08-08', 'Leadville', 'USA'),
('Sea Otter Classic', 'cycling', 'Festival', '2026-04-16', 'Monterey', 'USA'),
('Red Hook Crit Brooklyn', 'cycling', 'Criterium', '2026-05-09', 'Brooklyn', 'USA'),
('HYROX Salt Lake City', 'hyrox', 'Open', '2027-03-20', 'Salt Lake City', 'USA'),
('HYROX Philadelphia', 'hyrox', 'Open', '2027-04-17', 'Philadelphia', 'USA'),
('HYROX Cleveland', 'hyrox', 'Open', NULL, 'Cleveland', 'USA'),
('HYROX Pittsburgh', 'hyrox', 'Open', NULL, 'Pittsburgh', 'USA'),
('HYROX Raleigh', 'hyrox', 'Open', NULL, 'Raleigh', 'USA'),
('HYROX San Antonio', 'hyrox', 'Open', NULL, 'San Antonio', 'USA'),
('HYROX Sacramento', 'hyrox', 'Open', NULL, 'Sacramento', 'USA'),
('HYROX Oklahoma City', 'hyrox', 'Open', NULL, 'Oklahoma City', 'USA'),
('HYROX Memphis', 'hyrox', 'Open', NULL, 'Memphis', 'USA'),
('HYROX New Orleans', 'hyrox', 'Open', NULL, 'New Orleans', 'USA'),
('HYROX Jacksonville', 'hyrox', 'Open', NULL, 'Jacksonville', 'USA'),
('HYROX Birmingham UK', 'hyrox', 'Open', NULL, 'Birmingham', 'UK'),
('HYROX Manchester', 'hyrox', 'Open', NULL, 'Manchester', 'UK'),
('HYROX Glasgow', 'hyrox', 'Open', NULL, 'Glasgow', 'UK'),
('HYROX Rotterdam', 'hyrox', 'Open', NULL, 'Rotterdam', 'Netherlands'),
('HYROX Brussels', 'hyrox', 'Open', NULL, 'Brussels', 'Belgium'),
('HYROX Milan', 'hyrox', 'Open', NULL, 'Milan', 'Italy'),
('HYROX Munich', 'hyrox', 'Open', NULL, 'Munich', 'Germany'),
('HYROX Hamburg', 'hyrox', 'Open', NULL, 'Hamburg', 'Germany'),
('HYROX Cape Town', 'hyrox', 'Open', NULL, 'Cape Town', 'South Africa'),
('HYROX Auckland', 'hyrox', 'Open', NULL, 'Auckland', 'New Zealand'),
('HYROX Brisbane', 'hyrox', 'Open', NULL, 'Brisbane', 'Australia'),
('HYROX Perth', 'hyrox', 'Open', NULL, 'Perth', 'Australia'),
('HYROX Abu Dhabi', 'hyrox', 'Open', NULL, 'Abu Dhabi', 'UAE'),
('HYROX Riyadh', 'hyrox', 'Open', NULL, 'Riyadh', 'Saudi Arabia'),
('HYROX Seoul', 'hyrox', 'Open', NULL, 'Seoul', 'South Korea'),
('HYROX Taipei', 'hyrox', 'Open', NULL, 'Taipei', 'Taiwan'),
('HYROX São Paulo', 'hyrox', 'Open', NULL, 'São Paulo', 'Brazil'),
('HYROX Mexico City', 'hyrox', 'Open', NULL, 'Mexico City', 'Mexico'),
('HYROX Buenos Aires', 'hyrox', 'Open', NULL, 'Buenos Aires', 'Argentina');
